### ISSUE TITLE
1.14.1 Crash

### ISSUE THREAD

**Issue by el0c** [NinjaPhenix/CursedChests#18]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 5/14/19 2:04 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.class_2591$class_2592.method_11035(Ljava/util/function/Supplier;)Lnet/minecraft/class_2591$class_2592;
	at gd.rf.ninjaphenix.cursedchests.CursedChests.<clinit>(CursedChests.java:34)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:93)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gd.rf.ninjaphenix.cursedchests.CursedChests.<clinit>(CursedChests.java:34)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:93)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by el0c** [comment]
Somehow managed to press enter and submit the whole thing, sorry about that. 

Anywho, I seem to be crashing with your mod installed (which is a shame, it's been wonderful) 
Let me know if I can provide anything else or a longer log. 

This is fabric-1.14.1-build.4-0.4.7-build.147

**Comment by SDUBZ** [comment]
1.14 using fabric-loader-0.4.7+build.147-1.14.1+build.4 getting same
[crash-2019-05-15_16.48.02-client.txt](https://github.com/NinjaPhenix/CursedChests/files/3181210/crash-2019-05-15_16.48.02-client.txt)

**Comment by NinjaPhenix** [comment]
The mod isn't updated to 1.14.1 I'm working on a build however I'd like to allow worlds to be able to update from 1.14 to 1.14.1

**Comment by NinjaPhenix** [comment]
Released a new version for 1.14.1, old world chests will lose their contents and turn invisible (they should still be there), items should continue to exist and work normally. https://minecraft.curseforge.com/projects/cursed-chests
