### ISSUE TITLE
2.3.18 incompatible with REI v2.9.1 build 119+

### ISSUE THREAD

**Issue by VaiN474** [NinjaPhenix/CursedChests#19]
CursedChests 2.3.18 [1.14.1]
RoughlyEnoughItems 2.9.1 build 121
Fabric Loader 0.4.8 build 154
Fabric API 0.3.0 build 157a

Unable to access inventory of any cursed chests with the latest REI installed. Attempting to open the chests produces the following error in the log:
```
[main/FATAL]: Error executing task on Client
io.netty.util.IllegalReferenceCountException: refCnt: 0
  at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1417) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
  at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
  at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:812) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
  at net.minecraft.class_2540.readLong(class_2540.java:937) ~[intermediary-minecraft-1.14.1-client.jar:?]
  at net.minecraft.class_2540.method_10811(class_2540.java:176) ~[intermediary-minecraft-1.14.1-client.jar:?]
  at gd.rf.ninjaphenix.cursedchests.CursedChests.lambda$onInitialize$0(CursedChests.java:28) ~[CursedChests-2.3.18.jar:?]
  at net.fabricmc.fabric.impl.container.ContainerProviderImpl.createContainer(ContainerProviderImpl.java:95) ~[7f93ad59-4d91-47ee-89b4-f80c6ef0a337.jar:?]
  at net.fabricmc.fabric.impl.client.gui.ScreenProviderRegistryImpl.lambda$registerFactory$0(ScreenProviderRegistryImpl.java:56) ~[7f93ad59-4d91-47ee-89b4-f80c6ef0a337.jar:?]
  at net.fabricmc.fabric.impl.client.gui.ScreenProviderRegistryImpl.lambda$null$1(ScreenProviderRegistryImpl.java:75) ~[7f93ad59-4d91-47ee-89b4-f80c6ef0a337.jar:?]
  at net.minecraft.class_1255.method_18859(class_1255.java:135) [intermediary-minecraft-1.14.1-client.jar:?]
  at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.14.1-client.jar:?]
  at net.minecraft.class_1255.method_16075(class_1255.java:114) [intermediary-minecraft-1.14.1-client.jar:?]
  at net.minecraft.class_1255.method_5383(class_1255.java:99) [intermediary-minecraft-1.14.1-client.jar:?]
  at net.minecraft.class_310.method_1523(class_310.java:915) [intermediary-minecraft-1.14.1-client.jar:?]
  at net.minecraft.class_310.method_1514(class_310.java:411) [intermediary-minecraft-1.14.1-client.jar:?]
  at net.minecraft.client.main.Main.main(Main.java:154) [intermediary-minecraft-1.14.1-client.jar:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
  at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.8+build.154.jar:?]
  at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [fabric-loader-0.4.8+build.154.jar:?]
  at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.4.8+build.154.jar:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
  at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
  at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
  at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
Everything other than cursed chests continues to function as expected. Removing REI or downgrading to v2.9.1 Build 116 of REI resolves the issue. Not sure what the issue is, so I figured I'd start with the mod that is effected.

**Comment by NinjaPhenix** [comment]
I'm unable to replicate this with the same java version, mod versions and fabric version...
I would like to still look into this issue however so could you provide, your operating system (e.g. windows, linux, mac), a mod list and type of java (e.g. oracle java 8u211, openJDK)

**Comment by VaiN474** [comment]
I used a separate instance in mmc, so it's only the mods listed. Using windows 10, oracle java jre 8u211. In testing I also found this same error to occur with mpcs' backpacks with the same REI versions, so it may be an issue with REI not liking mod-added inventories or something.

**Comment by NinjaPhenix** [comment]
Well as far as I can tell, there's no difference between our instances meaning theres no way for me to recreate or even test the bug. Additionally it sounds like it could be an issue with the REI if it is happening for all modded screens. I'll take a quick look into recent REI changes to see if theres any changes that might cause this.

**Comment by shedaniel** [comment]
Does this happen on 1.14.2? I might have mistagged some REI versions.

**Comment by NinjaPhenix** [comment]
Going to close this as it doesn't sound like it is an issue with cursed chests.
